name: outline
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  agora_rtc_engine: ^5.0.1
  auto_direction: ^0.0.5
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.4
  dio: ^4.0.5
  dotted_border: ^2.0.0+2
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.11
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^9.4.0
  flutter_overlay_loader: ^1.0.3
  flutter_quill: ^4.1.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_tags: ^1.0.0-nullsafety.1
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  introduction_screen: ^2.0.0
  overlay_support: ^1.2.1
  percent_indicator: ^4.0.0
  permission_handler: ^9.2.0
  pull_to_refresh: ^2.0.0
  readmore: ^2.1.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
