// ignore: constant_identifier_names
const String fcm_server_key =
    "key=AAAARGfJI28:APA91bHNMhWGGvH2WoKxadOUld_LSuHUj6-dbUpxBJZCI91tNDEcfwAb9glhombHZ_C1mtXtJnLVI5pWu7Ivu6isj9rWsbOnJWGE1bt4KXQHf2j61vegxmWTMPb3qW42UUoOLFaKqaGB";
